matrix:
  include:
    - language: python
      sudo: true
      dist: trusty
      python: 3.5
      install:
        - pip3 install -r test/deploy_zstor_in_travis/requirements.txt
      before_script:
        - bash test/deploy_zstor_in_travis/run_tests.sh before
      script:
        - bash test/deploy_zstor_in_travis/run_tests.sh test

    - language: go
      sudo: true
      dist: trusty
      go: 1.11.x
      install: skip
      script:
        - env GO111MODULE=on make
        - env GO111MODULE=on make test

    - language: go
      sudo: true
      dist: trusty
      go: 1.11.x
      install: skip
      script: env GO111MODULE=on make testcov
      after_success: bash <(curl -s https://codecov.io/bash) -F unittests

    - language: go
      go: 1.11.x
      install: skip
      script:
        - env GO111MODULE=on go vet ./...
        - env GO111MODULE=on diff -u <(echo -n) <(gofmt -d $(find . -name "*\.go" | grep -v '\.git/'))
        - env GO111MODULE=on utils/scripts/ineffassign.sh
        - env GO111MODULE=on utils/scripts/copyright_check.sh .

    - language: go
      sudo: true
      dist: trusty
      go: 1.11.x
      install: skip
      script: env GO111MODULE=on make testclientrace

    - language: go
      sudo: true
      dist: trusty
      go: 1.11.x
      install: skip
      script: env GO111MODULE=on make testdaemonrace

    - language: go
      sudo: true
      dist: trusty
      go: 1.11.x
      install:
        - ./utils/scripts/install_protoc_unix.sh
      script: env GO111MODULE=on  make testcodegen
