
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[override]]
  name = "github.com/codegangsta/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.2.6"

[[constraint]]
  name = "github.com/coreos/pkg"
  version = "3.0.0"

[[constraint]]
  name = "github.com/dgraph-io/badger"
  branch = "master"

[[override]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.0.0"

[[override]]
  name = "github.com/docker/go-units"
  version = "0.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/gogo/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"

[[override]]
  name = "github.com/itsyouonline/identityserver"
  branch = "1.0.1"

[[override]]
  name = "github.com/justinas/alice"
  version = "1.0.0"

[[override]]
  name = "github.com/paulbellamy/ratecounter"
  version = "0.2.0"

[[constraint]]
  name = "github.com/pierrec/lz4"
  version = "=2.0.5"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  name = "github.com/templexxx/reedsolomon"
  revision = "0a1f6992d698b8e97bd97cbbd51fdac317959741"

[[override]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "=1.5.2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/validator.v2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  revision = "59cb774ae323e0a21179c6ce41384698c6827543"
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

# etcd client requires this version
[[override]]
  name = "github.com/ugorji/go"
  revision = "ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"

# it is OK to do this because we only use `redcon` package during the test
[[constraint]]
  branch = "zerodb-test"
  name = "github.com/iwanbk/redcon"
