namespace: default
datastor:
  spreading: "random"
  shards:
    - 127.0.0.1:5000
    - 127.0.0.1:5001
    - 127.0.0.1:5002
  pipeline:
    block_size: 4096
    compression:
      mode: default
    encryption:
      private_key: ab345678901234567890123456789012
    distribution:
      data_shards: 2
      parity_shards: 1
metastor:
  db:
    endpoints:
      - 127.0.0.1:2379
  encryption:
    private_key: ab345678901234567890123456789012
